package proyectocrud.CRUD;

import java.awt.FlowLayout;
import javax.swing.*;
import DB.APIDB;
/**
 *
 * @author mmppppss
 */
public class ReadList extends javax.swing.JFrame {

    /**
     * Creates new form Read
     */
    APIDB aaa;
    public ReadList() {
        this.setResizable(false);
        aaa = new APIDB();
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        BoxLayout a  = new BoxLayout(mainPanel, BoxLayout.Y_AXIS);
        mainPanel.setLayout(a);
        addArticlePanel("hola");
        addArticlePanel("holaaa2");
    }
    public void listArts(){
        String list[][] = aaa.getArts();
        for (String[] tupla : list) {
            JPanel tempPanel = new JPanel();
            JLabel title = new JLabel(tupla[0]);
            tempPanel.add(title);
            tempPanel.setVisible(true);
        }
            pack();
    }
    private void makelist(){
        
    }
    private void addArticlePanel(String title) {
        JPanel articlePanel = new JPanel();
        articlePanel.setLayout(new FlowLayout(FlowLayout.RIGHT));
        articlePanel.setSize(655, 40);
        articlePanel.setPreferredSize(articlePanel.getSize());
        articlePanel.setMinimumSize(articlePanel.getSize());
        articlePanel.setMaximumSize(articlePanel.getSize());
        articlePanel.setBackground(new java.awt.Color(80, 73, 69));
        JLabel titleLabel = new JLabel(title);
        articlePanel.add(titleLabel);

        JButton viewButton = new JButton("VER");
        JButton editButton = new JButton("EDITAR");
        JButton deleteButton = new JButton("BORRAR");

        viewButton.setBackground(new java.awt.Color(29, 32, 33));
        viewButton.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        viewButton.setForeground(new java.awt.Color(168, 153, 132));
        viewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocrud/assets/view.png"))); // NOI18N
        viewButton.setFocusPainted(false);
        viewButton.addActionListener((java.awt.event.ActionEvent evt) -> {
            System.out.println("view");
        });
        editButton.setBackground(new java.awt.Color(29, 32, 33));
        editButton.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(168, 153, 132));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocrud/assets/edit.png"))); // NOI18N
        editButton.setText("EDITAR");
        editButton.setFocusPainted(false);
        editButton.addActionListener((java.awt.event.ActionEvent evt) -> {
            System.out.println("edit");
        });
        deleteButton.setBackground(new java.awt.Color(29, 32, 33));
        deleteButton.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(168, 153, 132));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocrud/assets/delete.png"))); // NOI18N
        deleteButton.setText("BORRAR");
        deleteButton.setFocusPainted(false);
        deleteButton.addActionListener((java.awt.event.ActionEvent evt) -> {
            System.out.println("delete");
        });
        
        articlePanel.add(viewButton);
        articlePanel.add(editButton);
        articlePanel.add(deleteButton);

        mainPanel.add(articlePanel);
        mainPanel.add(Box.createVerticalStrut(15)); // Adding vertical space between panels
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));
        jPanel1.setForeground(new java.awt.Color(251, 241, 199));
        jPanel1.setMaximumSize(new java.awt.Dimension(720, 480));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 480));

        logo.setFont(new java.awt.Font("Source Code Pro Black", 0, 24)); // NOI18N
        logo.setForeground(new java.awt.Color(235, 219, 178));
        logo.setText("Informatica Blog Dashboard");

        addButton.setBackground(new java.awt.Color(29, 32, 33));
        addButton.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(168, 153, 132));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocrud/assets/create.png"))); // NOI18N
        addButton.setText("CREATE NEW");
        addButton.setFocusPainted(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        scrollPanel.setBackground(new java.awt.Color(60, 56, 54));
        scrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPanel.setPreferredSize(new java.awt.Dimension(680, 640));

        mainPanel.setBackground(new java.awt.Color(60, 56, 54));
        mainPanel.setMaximumSize(new java.awt.Dimension(670, 670));
        mainPanel.setMinimumSize(new java.awt.Dimension(670, 50));
        mainPanel.setPreferredSize(new java.awt.Dimension(670, 653));
        scrollPanel.setViewportView(mainPanel);
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logo)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Create c = new Create();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReadList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}